config/routes.rb
Rails.application.routes.draw do
  resources :sad_cats, only: [:index, :new, :create]

  get 'list_cats', to: 'sad_cats#list_cats'
  root 'sad_cats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/original_post.rb
class OriginalPost < ApplicationRecord
  enum post_type: %i(tweet tumblr)

  has_many :sad_cats
end

app/models/sad_cat.rb
class SadCat < ApplicationRecord
  self.per_page = 5

  belongs_to :original_tumblr, class_name: "OriginalPost"
  belongs_to :original_tweet, class_name: "OriginalPost"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sad_cats_controller.rb
class SadCatsController < ApplicationController
  before_filter :sanitize_params, only: [:create]

  def index
  end

  def new
    unimpressed_cat_post = TumblrCatGrabberService.new.call
    sad_tweet = TwitterSadGrabberService.new.call
    sad_picture_of_cat = SadCatProcessorService.new(cat_picture(unimpressed_cat_post), sad_tweet.text).call

    @sad_cat = SadCat.new(
        image: {
            path: sad_picture_of_cat,
        }.merge(cat_dimension(unimpressed_cat_post))
    )

    @original_tumblr = original_tumblr_attr(unimpressed_cat_post)
    @original_tweet = original_tweet_attr(sad_tweet)
  end

  def create
    SadCat.transaction do
      original_tweet = OriginalPost.find_or_create_by(original_tweet_params)
      original_tumblr = OriginalPost.find_or_create_by(original_tumblr_params)

      @sad_cat = SadCat.new(
          sad_cat_params.merge(
              original_tweet: original_tweet,
              original_tumblr: original_tumblr
          )
      )

      if @sad_cat.save!
        respond_to do |format|
          format.html { redirect_to sad_cats_path, notice: 'Great.. You brought a new sad cat into the world.' }
        end
      else
        render alert: 'Oh rats! something went wrong with server (hopefully not rats though).',
               status: :unprocessable_entity
      end
    end
  end

  def list_cats
    @sad_cats = SadCat.page(params[:page]).order('created_at DESC')

    render partial: 'sad_cats/partials/sad_cats_cards'
  end

  private

  def sad_cat_params
    params
        .require(:sad_cat)
        .permit(:creator,
                image: [:path, :width, :height]
        )
  end

  def original_tumblr_params
    params
        .require(:original_tumblr)
        .permit(original_tumblr_attr({}).keys)
  end

  def original_tweet_params
    params
        .require(:original_tweet)
        .permit(original_tweet_attr(Twitter::Tweet.new(id: nil)).keys)
  end

  def cat_picture(post)
    post['photos'].first['alt_sizes'].second['url']
  end

  def cat_dimension(post)
    {
        width: post['photos'].first['alt_sizes'].second['width'],
        height: post['photos'].first['alt_sizes'].second['height']
    }
  end

  def original_tumblr_attr(post)
    {
        account_name: post['blog_name'],
        url: post['short_url'],
        external_id: post['id'],
        post_type: OriginalPost.post_types[:tumblr]
    }
  end

  def original_tweet_attr(tweet)
    {
        account_name: tweet.user['screen_name'],
        url: tweet.url.to_s,
        external_id: tweet.id,
        post_type: OriginalPost.post_types[:tweet]
    }
  end

  def sanitize_params
    params['original_tweet']['external_id'] =  params['original_tweet']['external_id'].to_i
    params['original_tweet']['post_type'] =  params['original_tweet']['post_type'].to_i
    params['original_tumblr']['external_id'] =  params['original_tumblr']['external_id'].to_i
    params['original_tumblr']['post_type'] =  params['original_tumblr']['post_type'].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller_action_name
    "#{controller.controller_name} #{controller.action_name}"
  end
end

app/helpers/sad_cats_helper.rb
module SadCatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="layout-default">
  <head>
    <title>Cwhl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_action_name %>">
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sad_cats/index.html.erb
<header>
  <h1>Cats with a hard life</h1>
</header>
<nav>
  <%= link_to 'Generate a cat', new_sad_cat_path, { class: 'btn btn-primary'} %>
</nav>
<section id="pinBoard">

</section>
<div class="loader">
  <div class="spinner">
    <div class="bounce1"></div>
    <div class="bounce2"></div>
    <div class="bounce3"></div>
  </div>
</div>

app/views/sad_cats/new.html.erb
<header>
<h1>Sad Cat Generator</h1>
</header>
<section class="output">
  <img src="<%=image_path(@sad_cat.image['path'])%>" class="img-fluid rounded">
  <p> Cat from: <%=link_to  @original_tumblr[:url], @original_tumblr[:url] %></p>
  <p> Tweet from: <%=link_to @original_tweet[:url], @original_tweet[:url] %></p>
  <div class="actions-container">
      <a class="btn btn-primary" data-toggle="modal" data-target="#catCreationModal">Purrrfect! Save this sad cat</a>
      <%= link_to 'Pass! give me a sadder cat!', new_sad_cat_path,
                  method: :get , class: 'btn btn-primary' %>
  </div>
</section>
<%= render 'sad_cats/partials/create_cat_modal', local: {sad_cat: @sad_cat}%>

app/views/sad_cats/partials/_create_cat_modal.html.erb
<div id="catCreationModal" class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for @sad_cat, method: :post do |f| %>
          <div class="modal-header">
            <h5 class="modal-title">If you like it then put your name on it.</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= f.text_field :creator %>
            <!--<%= f.hidden_field :image, @sad_cat.image %>-->
            <%= f.fields_for :image do |image|%>
                <% @sad_cat.image.each do |key,value| %>
                  <%= image.hidden_field key.to_sym, value: value %>
                <% end %>
            <% end %>

            <% @original_tumblr.each do |key,value| %>
                <%= hidden_field_tag "original_tumblr[#{key}]",value %>
            <% end %>
            <% @original_tweet.each do |key,value| %>
                <%= hidden_field_tag "original_tweet[#{key}]",value %>
            <% end %>
          </div>
          <div class="modal-footer">
            <%= f.submit 'Ok. Done!', class: 'btn btn-primary' %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Nope, I changed my mind</button>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sad_cats/partials/_sad_cats_cards.html.erb
<% @sad_cats.each do | cat | %>
    <% if cat.image.present? %>
        <img width="<%=cat.image['width']%>"
             height="<%=cat.image['height']%>"
             src="<%=image_path(cat.image['path'])%>" class="rounded">
    <% end %>
<% end %>